In [1]:
import numpy as np

In [2]:
a=np.random.random((10,4))
a

array([[0.55269707, 0.54772361, 0.98002684, 0.19697413],
       [0.28770927, 0.07929153, 0.764722  , 0.9256423 ],
       [0.47377033, 0.80951071, 0.53731121, 0.16358845],
       [0.19058867, 0.82340839, 0.72274002, 0.05866694],
       [0.47342142, 0.22519919, 0.83382477, 0.18086772],
       [0.15773911, 0.66571492, 0.83586034, 0.88004644],
       [0.6627818 , 0.88704229, 0.51895742, 0.29546822],
       [0.90410974, 0.68012723, 0.24247989, 0.87554769],
       [0.0507415 , 0.35433516, 0.39900791, 0.62277415],
       [0.62712254, 0.11346302, 0.73323541, 0.46553218]])

In [3]:
a.shape

(10, 4)

In [4]:
a.size

40

In [5]:
a[0]

array([0.55269707, 0.54772361, 0.98002684, 0.19697413])

In [7]:
b=np.random.random((5,3,2))
b

array([[[0.96022057, 0.32357265],
        [0.94391164, 0.34532579],
        [0.58778981, 0.09889864]],

       [[0.7255811 , 0.96393407],
        [0.01237296, 0.84492895],
        [0.94266654, 0.41525484]],

       [[0.47996116, 0.43191374],
        [0.72285751, 0.07325477],
        [0.47420291, 0.12061482]],

       [[0.07923126, 0.37861171],
        [0.13744115, 0.24748599],
        [0.62104018, 0.80825134]],

       [[0.60957786, 0.75267726],
        [0.52558181, 0.59806295],
        [0.37647122, 0.15334737]]])

In [8]:
b.shape

(5, 3, 2)

In [9]:
b.size

30

In [10]:
c=np.random.random((2,3,4,5))
c

array([[[[0.93235363, 0.82021165, 0.11131105, 0.59389912, 0.8153785 ],
         [0.01365642, 0.92996946, 0.08345577, 0.79738541, 0.49739656],
         [0.34749746, 0.40212498, 0.62598784, 0.26846407, 0.92975562],
         [0.45582472, 0.64647367, 0.2010888 , 0.90631767, 0.30974292]],

        [[0.53345945, 0.31964712, 0.05363005, 0.35451206, 0.58250186],
         [0.92017837, 0.00648457, 0.18903492, 0.11582658, 0.54363101],
         [0.17295689, 0.19896724, 0.52480803, 0.64457698, 0.08085444],
         [0.08675363, 0.31158823, 0.77144649, 0.68376471, 0.45491282]],

        [[0.36346892, 0.56987802, 0.31900298, 0.64664533, 0.5777318 ],
         [0.86967721, 0.07318255, 0.61347175, 0.78215762, 0.27793372],
         [0.0217113 , 0.61779695, 0.70346103, 0.99897495, 0.89398684],
         [0.76763284, 0.68841067, 0.46354437, 0.80868411, 0.88339793]]],


       [[[0.97616478, 0.97280996, 0.45047066, 0.74122495, 0.63464455],
         [0.04115303, 0.59031949, 0.86392711, 0.05511782, 0.78103647]

In [11]:
a[:0]

array([], shape=(0, 4), dtype=float64)

In [12]:
a[:,0]

array([0.55269707, 0.28770927, 0.47377033, 0.19058867, 0.47342142,
       0.15773911, 0.6627818 , 0.90410974, 0.0507415 , 0.62712254])

In [13]:
a[0,:]

array([0.55269707, 0.54772361, 0.98002684, 0.19697413])

In [14]:
a[4][2]

0.8338247697580932

In [15]:
a[4,2]

0.8338247697580932

In [17]:
c[0][1][0][1]

0.3196471160846829

In [18]:
c[0,1,0,1]

0.3196471160846829

In [19]:
import pandas as pd

In [20]:
s=pd.Series(np.random.random(10))
s

0    0.626965
1    0.897748
2    0.586500
3    0.854758
4    0.815776
5    0.745175
6    0.697300
7    0.864464
8    0.307694
9    0.142530
dtype: float64

In [21]:
s.index=['a','b','c','d','e','f','g','h','i','j']
s

a    0.626965
b    0.897748
c    0.586500
d    0.854758
e    0.815776
f    0.745175
g    0.697300
h    0.864464
i    0.307694
j    0.142530
dtype: float64

In [23]:
columnas=['Col1','Col2','Col3','Col4','Col5']