In [25]:
import pandas as pd
import numpy as np

In [27]:
a=np.random.random((10,4))
print(a)

[[0.76073563 0.29168821 0.53441529 0.49660444]
 [0.38161067 0.45640641 0.14149635 0.47854926]
 [0.31415866 0.50897729 0.71252573 0.97379745]
 [0.5132379  0.50386845 0.75884414 0.90366158]
 [0.43092985 0.33493177 0.84704507 0.50019284]
 [0.30657108 0.71896017 0.44512682 0.82179051]
 [0.85299763 0.50749913 0.2746102  0.35115301]
 [0.41609094 0.42291829 0.74039304 0.59092742]
 [0.43588615 0.23157342 0.40237239 0.27735312]
 [0.03909068 0.31121183 0.40060175 0.32637379]]


In [31]:
hoteles = pd.DataFrame({'nombre':['Palace','Ritz','Pension Loli'],
                        'stars':[5,5,1],
                        'Precio':[800,900,30]
                       })
hoteles

nombre  stars  Precio
0        Palace      5     800
1          Ritz      5     900
2  Pension Loli      1      30

In [32]:
hoteles.dtypes

nombre    object
stars      int64
Precio     int64
dtype: object

In [33]:
hoteles.shape

(3, 3)

In [37]:
hoteles['Ratio']=hoteles.stars/hoteles.Precio
hoteles

nombre  stars  Precio     Ratio
0        Palace      5     800  0.006250
1          Ritz      5     900  0.005556
2  Pension Loli      1      30  0.033333

In [38]:
hoteles.sum()

nombre    PalaceRitzPension Loli
stars                         11
Precio                      1730
Ratio                  0.0451389
dtype: object

In [39]:
hoteles.describe()

stars      Precio     Ratio
count  3.000000    3.000000  3.000000
mean   3.666667  576.666667  0.015046
std    2.309401  476.060220  0.015841
min    1.000000   30.000000  0.005556
25%    3.000000  415.000000  0.005903
50%    5.000000  800.000000  0.006250
75%    5.000000  850.000000  0.019792
max    5.000000  900.000000  0.033333

In [40]:
display(hoteles.describe().T['min'])

stars      1.000000
Precio    30.000000
Ratio      0.005556
Name: min, dtype: float64

In [42]:
import json

In [43]:
a={'nombre':'Pepe','apellido':'Garcias'}

In [44]:
b=json.dumps(a)

In [45]:
type(b)

str

In [46]:
b

'{"nombre": "Pepe", "apellido": "Garcias"}'

In [47]:
json.loads(b)

{'nombre': 'Pepe', 'apellido': 'Garcias'}

In [48]:
!pip3 install openpyxl

     |████████████████████████████████| 174kB 727kB/s eta 0:00:01
  Stored in directory: /Users/eghm/Library/Caches/pip/wheels/34/ee/6c/1279f7b70ea72432c2cef15dd3d915477cb3771d1618f6b8ef
  Stored in directory: /Users/eghm/Library/Caches/pip/wheels/2a/77/35/0da0965a057698121fc7d8c5a7a9955cdbfb3cc4e2423cad39
Successfully built openpyxl et-xmlfile


In [52]:
hoteles.to_excel('alumnos_export.xlsx')

In [56]:
import pickle
color={'leon':'amarillo','gato':'rojo'}
pickle.dump(color,open('save.p','wb'))

In [58]:
color2=pickle.load(open('save.p','rb'))
color2

EOFError: Ran out of input

In [59]:
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')

In [ ]:
df=pd