In [1]:
import numpy as np

In [5]:
print(np.version.version)

1.17.3
True


In [7]:
a = np.random.random((2,3,5))
print(a)
b = np.ones((5,3,2))
print(b)
c = np.transpose(b)
print(c)
d = a + c
print(d)
d_max = np.max(d)  
d_min = np.min(d)  
d_mean = np.mean(d)
               
print(d_max)   
print(d_min)   
print(d_mean)  
f = np.empty((2,3,5))
print(f)             

[[[0.12320459 0.15663065 0.84536629 0.32724919 0.92830496]
  [0.81830762 0.70930999 0.80627474 0.34178127 0.85196786]
  [0.12293561 0.31446536 0.86708446 0.63972461 0.55559462]]

 [[0.83689099 0.23835381 0.21943955 0.88987976 0.53094559]
  [0.50870718 0.61910244 0.5063425  0.80844209 0.32429153]
  [0.10383237 0.40012591 0.35618944 0.72171477 0.23825133]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[1.12320459 1.15663065 1.84536629 1.32724919 1.92830496]
  [1.81830762 1.70930999 1.80627474 1.34178127 1.85196786]
  [1.12293561 1.31446536 1.86708446 1.63972461 1.55559462]]

 [[1.83689099 1.23835381 1.21943955 1.88987976 1.53094559]
  [1.50870718 1.61910244 1.5063425  1.80844209 1.32429153]
  [1.10383237 1.40012591 1.35618944 1.72171477 1.23825133]]]
1.9283

In [8]:
for v in f:                               
    for s in d:                           
        if (s > d_min) and  (s < d_mean): 
            v = 25                        
        elif (s > d_mean) and (s < d_max):
            v = 75                        
        elif s == d_mean:                 
            v = 50                        
        elif s == d_min:                  
            v = 0                         
        elif s == d_max:                  
            v = 100                       

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()